name: Microsoft Azure Publication
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: Arasaki-App-Server
  AZURE_WEBAPP_PACKAGE_PATH: Arasaki/Server/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.Arasaki_App_Server_5c9c }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: Arasaki/Server
jobs:
  Publish-To-Azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Install Dotnet WASM Tools
      run: dotnet workload install wasm-tools
    - name: Restore Dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Run Arasaki Bundler
      run: |
        cd Bundler
        npm i
        npm run build:release
    - name: Build App
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test App
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish Release Build
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish To Microsoft Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
