name: Microsoft Azure Publication
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: Arasaki-App-Server
  AZURE_WEBAPP_PACKAGE_PATH: UEFI/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.Arasaki_App_Server_5c9c }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: UEFI
jobs:
  Publish-To-Azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup .NET WASM
      run: dotnet workload install wasm-tools
    - name: Restore Submodules
      run: git submodule update --init --recursive
    - name: Restore Dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Restore NPM Packages
      run: |
        cd Bundler
        npm i
        cd ../OS/wwwroot-dev
        npm i
    - name: Run Arasaki Bundler
      run: |
        cd Bundler
        npm run build:release
    - name: Build Release Executable
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test Release Executable
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish Release Executable
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Arasaki Release Executable To Microsoft Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Arasaki Artifacts To Microsoft Azure
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
